config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"} do
    get "/signup" => "registrations#new",   :as => :new_user_registration
  end
  
  resources :carts, only: [:show, :destroy]
  resources :line_items, only: [:create, :destroy]
  resources :orders, only: [:show, :index, :new_order]
  resources :categories, only: [:show]
  resources :books, only: [:show] do
    resources :ratings, only: [:new, :show, :create]
  end
  resources :authors, only: [:show]
  resources :address, only: [:update]
  
  put 'carts/:id/update_items' => "carts#update_items", as: 'update_carts_items'
  
  root 'home#bestsellers'
  
  get 'home/shop' => 'home#shop' , as: 'shopping'
  
  get 'new_order/:id' => 'orders#new_order', as: 'new_order_show', method: :get
    
  resources :checkouts, only: [:show, :create]
  
  get '/:locale' => 'application#change_language', as: 'change_language'
end

app/controllers/home_controller.rb
# HomeController
class HomeController < ApplicationController
  def bestsellers
    @bestsellers = BookDecorator.decorate_collection(Book.bestsellers)
  end
  def shop
    @categories = Category.all
    @books = Book.all
  end
end

app/views/home/bestsellers.html.erb
<div id="shopping">
<div class="best">
  <div id="owl-demo" class="owl-carousel owl-theme"> 
    <% @bestsellers.each do |book| %>
      <div>
        <div class="book_info">
          <div class="book_title">
            <%= book.title %> 
          </div> <%= t(:by) %> <%= link_to book.authors_link, author_path(book.author.id) %>
        </div>
        <div class="cover_desc">
          <div class="cover">
            <%= link_to book do %>
              <%= cl_image_tag("bookshop/#{book.cover_line}", :secure => true, :width => 180, :height => 250, :crop => :fill) %>
            <% end %>
          </div>
          <div class="desc">
            <%= book.description %>
          </div>
          <div class="to_cart">
            <div class="book_ord">
              <div class="boldy">$ <%= book.price %></div>                      
            </div>
            <% if book.quantity == 0 %>
              <div class="sold_out"></div>
            <% else %>
              <%= form_tag(line_items_path(book_id: book), method: :post) do %>
              <%= number_field_tag(:new_quantity, 1, in: 1..book.quantity, step: 1, :style => "width: 50px;") %>
                <div class="actions">
                  <%= submit_tag( t(:add_to_cart) ) %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="space"></div>
  <p><%=t :welcome %></p>
</div>
</div>

app/views/home/shop.html.erb
<div id="shopping">
  <ol class="breadcrumb">
    <li><%= link_to t(:home_page), root_path %></li>
    <li class="active"> <%= t(:shopping) %> </li>
  </ol>
  
  <div class="shop">
    <% @books.each do |book| %>
      <div id="shop_item">
        <div class="cover_item"> 
          <% if book.quantity == 0 %>
            <div class="sold_out_in_shop"></div>
          <% end %>
          <%= link_to book do %>
            <%= cl_image_tag("bookshop/#{book.cover_line}", :secure => true, :width => 180, :height => 250, :crop => :fill) %>
          <% end %>
        </div>
        <div class="title_item"> 
          <%= link_to book.title, book %>
        </div>
        <div class="price_item">
          <div class="boldy">$<%= book.price %></div>
        </div>
      </div>
    <% end %>
    <div id="pages">
      
    </div>
  </div>
  
  <div id="categories">
    <p><%= t(:categories) %></p>
    <ol class="links_cat">
      <% @categories.each do |category| %>
        <li>
          <%= link_to category.title, category %>
        </li>
      <% end %>
    </ol>
  </div>
</div>