config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"} do
    get "/signup" => "registrations#new",   :as => :new_user_registration
  end
  
  resources :carts, only: [:show, :destroy]
  resources :line_items, only: [:create, :destroy]
  resources :orders, only: [:show, :index, :new_order]
  resources :categories, only: [:show]
  resources :books, only: [:show] do
    resources :ratings, only: [:new, :show, :create]
  end
  resources :authors, only: [:show]
  resources :address, only: [:update]
  
  put 'carts/:id/update_items' => "carts#update_items", as: 'update_carts_items'
  
  root 'home#bestsellers'
  
  get 'home/shop' => 'home#shop' , as: 'shopping'
  
  get 'new_order/:id' => 'orders#new_order', as: 'new_order_show', method: :get
    
  resources :checkouts, only: [:show, :create]
  
  get '/:locale' => 'application#change_language', as: 'change_language'
end

app/models/rating.rb
# Rating
class Rating < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  ratyrate_rateable 'grade'

  validates :review, length: { maximum: 500, message: I18n.t(:review_length) }
  validates :review, presence: true
  validates :headline, presence: true
  validates_presence_of :grade

  scope :checking, -> { where(admin_checking: true) }
end

app/controllers/ratings_controller.rb
# RatingsController
class RatingsController < ApplicationController
  load_and_authorize_resource :book
  load_and_authorize_resource :rating, through: :book

  def show
    @rating = Rating.find(params[:id]).decorate
  end

  def new
    @rating = Rating.new
  end

  def create
    @rating = Rating.new(rating_params)
    @rating.grade = params[:score]
    if @rating.save
      redirect_to book_path(@rating.book_id)
      flash[:notice] = t(:rating_saved)
    else
      redirect_to new_book_rating_path(params[:book_id])
      flash[:alert] = t(:rating_not_saved)
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:headline, :review, :book_id, :user_id)
  end
end

app/views/ratings/_form.html.erb
<%= form_for @rating, url: book_ratings_path do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>
      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :book_id, value: params[:book_id]%>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <%= f.label t(:headline) %><br>
    <%= f.text_field :headline %>
  </div>
  <div class="field">
    <div><%= rating_for @rating, "grade", stars: 5, score: 5, star_path: '/images/ratyrate' %></div>
  </div>

  <div class="field">
    <%= f.label t(:review) %><br>
    <%= f.text_area :review, cols: "70", rows: "5", :maxlength => 500 %>
  </div>


  <div class="actions">
    <%= f.submit t(:new_rating) %> <%= t(:or) %> <%= link_to t(:cancel), book_path(params[:book_id]) %>
  </div>
<% end %>

app/views/ratings/new.html.erb
<div class="outside">
  <h1><%= t(:new_rating)%></h1>
  <%= render 'form' %>
</div>

app/views/ratings/show.html.erb
<div class="outside"> 
<div class="reviews">
  <div class="stars">
    <%= t(:rating)%>: <div class="grade"><%= @rating.grade %></div>
  </div>
  <div class="headline"><%= @rating.headline %></div>
  <div class="rev_create"><%= l(@rating.created_at, format: :short)%></div>
  <div class="author">
    <%=t(:by)%>
      <%=link_to @rating.author_name, book_rating_path(@rating.book.id, @rating.id) %>
  </div>
  <div class="rev_text"><%= @rating.review %></div>
</div>
  <%= link_to t(:to_book), book_path(params[:book_id]) %>
</div>