config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"} do
    get "/signup" => "registrations#new",   :as => :new_user_registration
  end
  
  resources :carts, only: [:show, :destroy]
  resources :line_items, only: [:create, :destroy]
  resources :orders, only: [:show, :index, :new_order]
  resources :categories, only: [:show]
  resources :books, only: [:show] do
    resources :ratings, only: [:new, :show, :create]
  end
  resources :authors, only: [:show]
  resources :address, only: [:update]
  
  put 'carts/:id/update_items' => "carts#update_items", as: 'update_carts_items'
  
  root 'home#bestsellers'
  
  get 'home/shop' => 'home#shop' , as: 'shopping'
  
  get 'new_order/:id' => 'orders#new_order', as: 'new_order_show', method: :get
    
  resources :checkouts, only: [:show, :create]
  
  get '/:locale' => 'application#change_language', as: 'change_language'
end

app/models/cart.rb
# Cart
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_one :coupon, dependent: :destroy
  belongs_to :user
  has_attached_file :image,
                    styles: { icon: '32x32' },
                    default_url: 'http://res.cloudinary.com/nmetau/image/upload/c_scale,h_32,w_32/v1457165066/bookshop/basket.png'

  def update_items_quantity(ids_with_quantity)
    @items_ids = ids_with_quantity.keys
    @items_ids.each do |item_id|
      line_item = LineItem.find_by(id: item_id.to_i)
      line_item.update_attributes(quantity: ids_with_quantity[:"#{item_id}"])
    end
  end
end

app/controllers/carts_controller.rb
# CartsController
class CartsController < ApplicationController
  include CartsHelper
  load_and_authorize_resource

  def show
    session[:last_step] ||= 'address'
  end

  def destroy
    return redirect_to cart_url, alert: I18n.t(:already_empty) if carts_items.empty?
    carts_items.destroy_all
    redirect_to cart_url
    flash[:notice] = t(:cart_cleared)
  end

  def update_items
    return redirect_to root_path if @cart.nil? || params[:ids].nil?
    @cart.update_items_quantity(params[:ids])
    @cart.coupon = Coupon.find_by(code: params[:coupon][:code], user_id: current_user.id)
    if invalid_coupon_code
      flash[:notice] = t(:quantity_changed)
    else
      flash[:alert] = t(:coupon_code_is_not_right)
    end
    redirect_to :back
  end

  private

  def invalid_coupon_code
    params[:coupon][:code].to_s.strip.empty? && @cart.coupon.nil?
  end
end

app/helpers/carts_helper.rb
# CartsHelper
module CartsHelper
  def sub_total
    return 0 if carts_items.count.zero?
    @sub_total = get_items_price(carts_items)
  end

  def get_items_price(items)
    items.collect { |book| book.price * book.quantity }.sum(:price).round(2)
  end

  def quantity_incart
    @quantity = carts_items.sum(:quantity)
  end

  def carts_items
    current_user.cart.line_items
  end

  def current_cart
    current_user.cart
  end

  def cart_fully
    return t(:empty) if carts_items.count.zero?
    "(#{quantity_incart})" + "$#{sub_total}"
  end

  def coupon_code_value
    current_cart.coupon.nil? ? nil : current_cart.coupon.code
  end

  def discount
    current_cart.coupon.nil? ? 0 : current_cart.coupon.discount
  end

  def sub_total_with_discount
    @discount = (sub_total * discount) / 100
    total = sub_total - @discount
    total.round(2)
  end
end

app/views/carts/show.html.erb
<div class="checkout">
  <% if @cart.line_items.count != 0 %>
    <table class = "cart">
      <th><%= t(:book) %></th>
      <th><%= t(:price) %></th>
      <th><%= t(:qty) %></th>
      <th><%= t(:total) %></th>

      <%= form_for @cart, url: update_carts_items_path(@cart.id), method: :put do |f| %>
      <%= fields_for :ids do |id| %>
        <% carts_items.each do |item| %>
          <tr>
            <td>
              <div class="cover">
                <%= link_to cl_image_tag("bookshop/#{item.book.cover_line}", :secure => true, :width => 180, :height => 250, :crop => :fill), item.book %>
              </div>
              <div class="book_info_in_cart">
                <div class="book_title">
                  <%= item.book.title %>
                </div>
                <div class = "desc">
                  <%= item.book.description %>
                </div>
              </div>
            </td>
            <td>
              <%= item.book.price %>
            </td>
            <td>
              <div class = "update">
                <%= id.number_field :"#{item.id}", value: item.quantity, in: 1..item.book.quantity, step: 1, :style => "width: 50px;" %>
              </div>
            </td>
            <td>
              <%= item.book.price * item.quantity %>
            </td>
            <td>
              <%= link_to 'X', line_item_path(id: item.id), method: :delete,  :style => "color: #000" %>
            </td>
          </tr>
        <% end %>
      <% end %>
      <div class="update_items">
        <%= fields_for :coupon do |coupon| %>
          <%= coupon.text_field :code, value: coupon_code_value, :style => "width: 100px; height: 29px;", placeholder: t(:coupon) %>
        <% end %>
        <%= f.submit t(:update), method: :put %>
      </div>
    <% end %>
    </table>
    <ul class="sub_total">
      <li><%= t(:subtotal)%> : <div class="price_right">$ <%= sub_total %></div></li>
      <li><%= t(:discount)%> : <div class="price_right"><%= discount %> %</div></li>
      <li><%= t(:total)%> : <div class="price_right">$ <%= sub_total_with_discount %></div></li>
    </ul>
    <div class="before_order">
      <div class="left_buttons">
        <div><%= button_to t(:empty_cart), cart_path, method: :delete %></div>
        <div><%= button_to t(:continue_shop), shopping_path, method: :get %></div>
      </div>
      <div class="right_buttons">
        <div><%= button_to t(:checkout), checkout_path(session[:last_step]), method: :get %></div>
      </div>
    </div> 
  <% else %>
    <p style="text-align: center;"><%= t(:cart_is_empty)%></p>
  <% end %>
</div>