config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"} do
    get "/signup" => "registrations#new",   :as => :new_user_registration
  end
  
  resources :carts, only: [:show, :destroy]
  resources :line_items, only: [:create, :destroy]
  resources :orders, only: [:show, :index, :new_order]
  resources :categories, only: [:show]
  resources :books, only: [:show] do
    resources :ratings, only: [:new, :show, :create]
  end
  resources :authors, only: [:show]
  resources :address, only: [:update]
  
  put 'carts/:id/update_items' => "carts#update_items", as: 'update_carts_items'
  
  root 'home#bestsellers'
  
  get 'home/shop' => 'home#shop' , as: 'shopping'
  
  get 'new_order/:id' => 'orders#new_order', as: 'new_order_show', method: :get
    
  resources :checkouts, only: [:show, :create]
  
  get '/:locale' => 'application#change_language', as: 'change_language'
end

app/views/layouts/_menu.html.erb
<div id="name"><h1><%=t :site_name %></h1></div>
<div id="root">
  <div id="home">
    <%= link_to t(:home_page), root_path %>
  </div>
  <div class="border"></div>
  <div id="route_shop">
    <%= link_to t(:shopping), shopping_path %>
  </div>
</div>
<div class="settings">  
  <% if user_signed_in? %>
    <% if !current_user.admin %>
      <div id="basket">
        <%= link_to image_tag( current_cart.image.url ), cart_path(id: current_user.id ) %> <%= t :cart %>
        <%= cart_fully %>
      </div>
      <%= link_to t(:settings), edit_user_registration_path %>
      <div class="border"></div>
      <%= link_to t(:orders), orders_path %>
      <div class="border"></div>
      <%= link_to t(:sign_out),  destroy_user_session_path,:method => :delete %>
      <div class="langueges"><%= link_to(t(:russian), change_language_path(:ru))%> | <%= link_to(t(:english), change_language_path(:en))%></div>
    <% elsif current_user.admin %>
      <%= link_to t(:control_panel), rails_admin.dashboard_path %>
      <div class="border"></div>
      <%= link_to t(:sign_out),  destroy_user_session_path,:method => :delete %>
    <% else %>
      <%= link_to t(:sign_out), destroy_user_session_path,:method => :delete %>
    <% end %>
  <% else %> 
    <%= link_to t(:sign_up), new_user_registration_path %>
    <div class="border"></div>
    <%= link_to t(:login), new_user_session_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/menu" %>
    </div>
    <div class="space"></div>
    <% if notice %>
      <div class="alert alert-info"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning"><%= alert %></div>
    <% end %>
    <%= yield %>
  </body>
</html>